export interface TarotCard {
  name: string;
  arcana: "major" | "minor";
  suit?: "cups" | "wands" | "swords" | "pentacles";
  number?: number;
  keywords: string[];
  meaningUpright: string;
  meaningReversed: string;
  romanticFlavor: string; // companion-specific romantic/sensual interpretation
}

export const TAROT_CARDS: TarotCard[] = [
  // ── MAJOR ARCANA ──
  { name: "The Fool", arcana: "major", number: 0, keywords: ["beginnings", "spontaneity", "trust"], meaningUpright: "New beginnings, leaping into the unknown with open arms.", meaningReversed: "Recklessness, naivety, missed opportunities.", romanticFlavor: "A thrilling new connection is forming — surrender to it without overthinking." },
  { name: "The Magician", arcana: "major", number: 1, keywords: ["willpower", "desire", "manifestation"], meaningUpright: "You have every tool you need to manifest what you want.", meaningReversed: "Manipulation, untapped potential, illusion.", romanticFlavor: "Your desire has real magnetic force right now — use it. Someone notices." },
  { name: "The High Priestess", arcana: "major", number: 2, keywords: ["intuition", "mystery", "subconscious"], meaningUpright: "Trust what you feel beneath the surface. Secrets are worth exploring.", meaningReversed: "Hidden motives, suppressed feelings, disconnection.", romanticFlavor: "There's a slow, deep pull between you and someone — an unspoken tension waiting to bloom." },
  { name: "The Empress", arcana: "major", number: 3, keywords: ["sensuality", "abundance", "nurturing"], meaningUpright: "Pleasure, beauty, and sensual abundance are yours to enjoy.", meaningReversed: "Neglected self-care, creative block, smothering.", romanticFlavor: "Indulge every sense. This is a season of warmth, touch, and being wholly desired." },
  { name: "The Emperor", arcana: "major", number: 4, keywords: ["authority", "stability", "structure"], meaningUpright: "Steady authority creates safety — and safety is deeply attractive.", meaningReversed: "Control issues, rigidity, coldness.", romanticFlavor: "Someone's quiet strength is drawing you in. Stability can be intensely seductive." },
  { name: "The Hierophant", arcana: "major", number: 5, keywords: ["tradition", "commitment", "belief"], meaningUpright: "Deeper commitment and shared values strengthen connection.", meaningReversed: "Rebellion, non-conformity, blind faith.", romanticFlavor: "A bond that moves beyond surface desire — this could be something that truly lasts." },
  { name: "The Lovers", arcana: "major", number: 6, keywords: ["love", "union", "choice"], meaningUpright: "A passionate connection, a choice made with both heart and body.", meaningReversed: "Imbalance, misalignment, difficult choices.", romanticFlavor: "The spark is undeniable. This card whispers of deep physical and emotional union." },
  { name: "The Chariot", arcana: "major", number: 7, keywords: ["willpower", "victory", "momentum"], meaningUpright: "Drive and focus win the night. You are moving toward exactly what you want.", meaningReversed: "Aggression, lack of control, scattered energy.", romanticFlavor: "You're pursuing something — or someone — with full force. That confidence is irresistible." },
  { name: "Strength", arcana: "major", number: 8, keywords: ["courage", "inner power", "compassion"], meaningUpright: "Gentle courage is the most powerful seduction of all.", meaningReversed: "Self-doubt, weakness, raw impulse.", romanticFlavor: "True intimacy requires vulnerability — and right now, that vulnerability is your greatest strength." },
  { name: "The Hermit", arcana: "major", number: 9, keywords: ["introspection", "guidance", "wisdom"], meaningUpright: "Honest reflection reveals what you truly need from connection.", meaningReversed: "Isolation, loneliness, withdrawn nature.", romanticFlavor: "Time alone has clarified something important about what you want. Trust that clarity." },
  { name: "Wheel of Fortune", arcana: "major", number: 10, keywords: ["cycles", "fate", "turning point"], meaningUpright: "The wheel turns — a significant moment in your love story is approaching.", meaningReversed: "Resistance to change, bad luck, clinging to the past.", romanticFlavor: "Fate is weaving something unexpected. An encounter you can't quite explain is destined." },
  { name: "Justice", arcana: "major", number: 11, keywords: ["fairness", "truth", "balance"], meaningUpright: "Honesty between two people creates real, lasting intimacy.", meaningReversed: "Dishonesty, unfair treatment, imbalance.", romanticFlavor: "A truthful conversation opens doors that polite silence never could." },
  { name: "The Hanged Man", arcana: "major", number: 12, keywords: ["pause", "surrender", "new perspective"], meaningUpright: "Surrender to the moment completely — that's where the magic lives.", meaningReversed: "Stalling, resistance, wasted effort.", romanticFlavor: "Let yourself be vulnerable. The one who yields fully is the one who feels everything." },
  { name: "Death", arcana: "major", number: 13, keywords: ["transformation", "endings", "rebirth"], meaningUpright: "Something is ending so something far more alive can begin.", meaningReversed: "Resistance to change, stagnation, fear.", romanticFlavor: "A past dynamic is dissolving. What emerges in its place will be rawer, realer, and far more electric." },
  { name: "Temperance", arcana: "major", number: 14, keywords: ["balance", "patience", "moderation"], meaningUpright: "The slow burn is the hottest kind. Build with patience.", meaningReversed: "Excess, impatience, lack of harmony.", romanticFlavor: "You're blending beautifully with someone. The chemistry is slow and irresistible — let it simmer." },
  { name: "The Devil", arcana: "major", number: 15, keywords: ["temptation", "shadow", "desire"], meaningUpright: "Your shadow desires are valid — and exploring them honestly is freeing.", meaningReversed: "Detachment, reclaiming power, breaking free.", romanticFlavor: "A raw, magnetic pull. The Devil card says: give in to what you actually want, not what you're supposed to." },
  { name: "The Tower", arcana: "major", number: 16, keywords: ["upheaval", "revelation", "chaos"], meaningUpright: "A sudden revelation breaks down illusion and leaves only truth.", meaningReversed: "Averting disaster, resisting change.", romanticFlavor: "Something is about to shatter a comfortable illusion between you — and what's underneath is more real and more electric." },
  { name: "The Star", arcana: "major", number: 17, keywords: ["hope", "renewal", "inspiration"], meaningUpright: "After difficulty comes a beautiful, healing openness.", meaningReversed: "Despair, hopelessness, disconnection.", romanticFlavor: "You are becoming someone worthy of deep love — and someone already sees that in you." },
  { name: "The Moon", arcana: "major", number: 18, keywords: ["illusion", "subconscious", "mystery"], meaningUpright: "The subconscious is speaking. Your dreams about this person are trying to tell you something.", meaningReversed: "Confusion lifting, hidden truths surfacing.", romanticFlavor: "Night is where the real version of this connection lives. Trust the dark, mysterious pull." },
  { name: "The Sun", arcana: "major", number: 19, keywords: ["joy", "vitality", "success"], meaningUpright: "Pure warmth, joy, and the kind of confidence that makes you magnetic.", meaningReversed: "Temporary clouding, ego, false optimism.", romanticFlavor: "You are radiant right now. Someone finds that completely irresistible — let them." },
  { name: "Judgement", arcana: "major", number: 20, keywords: ["rebirth", "inner calling", "reckoning"], meaningUpright: "A second chance — or a new level of honesty — is calling to you.", meaningReversed: "Self-doubt, ignoring the call, harsh self-judgment.", romanticFlavor: "This is the moment to say what you actually feel. The one who hears you is ready." },
  { name: "The World", arcana: "major", number: 21, keywords: ["completion", "achievement", "wholeness"], meaningUpright: "A cycle of connection reaches its most complete, beautiful form.", meaningReversed: "Incompletion, shortcuts, carrying old wounds.", romanticFlavor: "A bond that feels genuinely whole — emotional, physical, and deeply satisfying. You're there." },

  // ── CUPS ──
  { name: "Ace of Cups", arcana: "minor", suit: "cups", number: 1, keywords: ["new love", "emotional beginning", "overflow"], meaningUpright: "A new emotional beginning — a cup overflowing with possibility.", meaningReversed: "Blocked emotions, missed connection, emptiness.", romanticFlavor: "A new sexual and emotional beginning is pouring itself into your life. Open up." },
  { name: "Two of Cups", arcana: "minor", suit: "cups", number: 2, keywords: ["partnership", "mutual attraction", "chemistry"], meaningUpright: "Deep mutual attraction — two people recognizing something rare in each other.", meaningReversed: "Imbalance, incompatibility, broken bond.", romanticFlavor: "The chemistry here is undeniable. Two people drawn to each other with equal intensity." },
  { name: "Three of Cups", arcana: "minor", suit: "cups", number: 3, keywords: ["celebration", "pleasure", "connection"], meaningUpright: "Joy, pleasure, and the sweetness of being wanted.", meaningReversed: "Overindulgence, isolation, gossip.", romanticFlavor: "This is a season of pleasure — let yourself be celebrated and desired without guilt." },
  { name: "Four of Cups", arcana: "minor", suit: "cups", number: 4, keywords: ["apathy", "contemplation", "re-evaluation"], meaningUpright: "A moment of quiet before you recognize what's right in front of you.", meaningReversed: "New possibilities, awakening, clarity.", romanticFlavor: "You may be overlooking something precious. Look up — someone is waiting for you to notice them." },
  { name: "Five of Cups", arcana: "minor", suit: "cups", number: 5, keywords: ["grief", "loss", "regret"], meaningUpright: "Grief over what was lost, but not everything is gone — look at what remains.", meaningReversed: "Acceptance, moving forward, resilience.", romanticFlavor: "Heartache is real, but it makes you deeper. What remains of this connection is worth your attention." },
  { name: "Six of Cups", arcana: "minor", suit: "cups", number: 6, keywords: ["nostalgia", "innocence", "reunion"], meaningUpright: "A return — to someone, to a feeling, to the version of yourself that loved freely.", meaningReversed: "Stuck in the past, unrealistic nostalgia.", romanticFlavor: "Someone from your past is still alive in your desires. Or this new connection feels familiar in a soul-level way." },
  { name: "Seven of Cups", arcana: "minor", suit: "cups", number: 7, keywords: ["fantasy", "illusion", "desire"], meaningUpright: "Many tempting possibilities — but clarity about what you really want is needed.", meaningReversed: "Reality check, clear choice, decisiveness.", romanticFlavor: "You're surrounded by fantasies. Pick the one that actually feeds you, not just excites you briefly." },
  { name: "Eight of Cups", arcana: "minor", suit: "cups", number: 8, keywords: ["withdrawal", "moving on", "deeper meaning"], meaningUpright: "Walking away from what no longer satisfies to find something real.", meaningReversed: "Avoidance, fear of abandonment, aimlessness.", romanticFlavor: "You deserve more than 'almost enough.' Moving on is not failure — it's self-respect." },
  { name: "Nine of Cups", arcana: "minor", suit: "cups", number: 9, keywords: ["satisfaction", "wish fulfilled", "pleasure"], meaningUpright: "The wish card — emotional and physical satisfaction is within reach.", meaningReversed: "Overindulgence, shallowness, unfulfillment.", romanticFlavor: "Your desires are about to be met — fully and deeply. The 'wish fulfilled' card is here." },
  { name: "Ten of Cups", arcana: "minor", suit: "cups", number: 10, keywords: ["harmony", "bliss", "lasting love"], meaningUpright: "Deep, lasting emotional fulfillment — the kind of love that truly satisfies.", meaningReversed: "Broken home, dysfunction, shattered ideals.", romanticFlavor: "This connection has the potential to become something genuinely sustaining and deeply beautiful." },

  // ── WANDS ──
  { name: "Ace of Wands", arcana: "minor", suit: "wands", number: 1, keywords: ["passion", "inspiration", "new fire"], meaningUpright: "Raw creative and sexual energy igniting something new.", meaningReversed: "Delays, creative block, lack of spark.", romanticFlavor: "A surge of raw desire — this connection is pure heat and momentum. Don't hold back." },
  { name: "Two of Wands", arcana: "minor", suit: "wands", number: 2, keywords: ["vision", "expansion", "planning"], meaningUpright: "You're standing at the edge of something exciting — with someone.", meaningReversed: "Fear of the unknown, lack of planning.", romanticFlavor: "You can feel the potential of where this could go. Step into it together." },
  { name: "Three of Wands", arcana: "minor", suit: "wands", number: 3, keywords: ["progress", "expansion", "foresight"], meaningUpright: "Your desires are on their way to you — keep going.", meaningReversed: "Delays, setbacks, frustration.", romanticFlavor: "What you've been building toward emotionally is arriving. Your patience is being rewarded." },
  { name: "Four of Wands", arcana: "minor", suit: "wands", number: 4, keywords: ["celebration", "homecoming", "joy"], meaningUpright: "Coming home to someone who genuinely wants you there.", meaningReversed: "Instability, conflict, lack of support.", romanticFlavor: "A warm, joyful reunion — or the beginning of a connection that feels comfortable and electric." },
  { name: "Five of Wands", arcana: "minor", suit: "wands", number: 5, keywords: ["conflict", "competition", "tension"], meaningUpright: "Some friction — but the friction is alive and charged.", meaningReversed: "Avoiding conflict, inner tension, suppressed desire.", romanticFlavor: "The tension between you two isn't just conflict — it's chemistry trying to find its form." },
  { name: "Six of Wands", arcana: "minor", suit: "wands", number: 6, keywords: ["victory", "confidence", "recognition"], meaningUpright: "You are at your most magnetic — and the right people notice.", meaningReversed: "Fall from grace, ego, lack of confidence.", romanticFlavor: "Right now you are radiantly desirable. Someone is watching you and can't look away." },
  { name: "Seven of Wands", arcana: "minor", suit: "wands", number: 7, keywords: ["perseverance", "defense", "conviction"], meaningUpright: "Stand your ground — what you feel is worth fighting for.", meaningReversed: "Overwhelmed, giving up, defensive walls.", romanticFlavor: "Don't let doubt make you retreat from this. What you want is real, and you deserve to pursue it." },
  { name: "Eight of Wands", arcana: "minor", suit: "wands", number: 8, keywords: ["speed", "momentum", "swift action"], meaningUpright: "Things are moving fast — this connection is accelerating.", meaningReversed: "Delays, frustration, miscommunication.", romanticFlavor: "Rapid escalation. Messages flying, hearts racing. This is the card of electric momentum." },
  { name: "Nine of Wands", arcana: "minor", suit: "wands", number: 9, keywords: ["resilience", "persistence", "guarded"], meaningUpright: "You've been through a lot, but you're still standing — still open.", meaningReversed: "Exhaustion, giving up, paranoia.", romanticFlavor: "Your past has made you guarded, but someone here is worth the risk of opening again." },
  { name: "Ten of Wands", arcana: "minor", suit: "wands", number: 10, keywords: ["burden", "responsibility", "overwhelm"], meaningUpright: "You're carrying a heavy load — it's okay to set some of it down.", meaningReversed: "Burning out, hiding true feelings, overstress.", romanticFlavor: "Let someone in to help you carry what you've been holding. That vulnerability is intimacy." },

  // ── SWORDS ──
  { name: "Ace of Swords", arcana: "minor", suit: "swords", number: 1, keywords: ["clarity", "truth", "breakthrough"], meaningUpright: "A cut-through moment — pure honest clarity about what you want.", meaningReversed: "Confusion, clouded thinking, miscommunication.", romanticFlavor: "Say the true thing. This level of directness is deeply attractive to the right person." },
  { name: "Two of Swords", arcana: "minor", suit: "swords", number: 2, keywords: ["indecision", "stalemate", "balance"], meaningUpright: "A difficult choice that can't be avoided much longer.", meaningReversed: "Indecision broken, information revealed, truth surfaces.", romanticFlavor: "You're holding yourself back from a decision. Both paths involve feeling something deeply." },
  { name: "Three of Swords", arcana: "minor", suit: "swords", number: 3, keywords: ["heartbreak", "grief", "pain"], meaningUpright: "Pain that is real and must be felt before it can heal.", meaningReversed: "Recovery, forgiveness, releasing grief.", romanticFlavor: "Heartbreak leaves marks — but those marks also prove you were real and open enough to feel." },
  { name: "Four of Swords", arcana: "minor", suit: "swords", number: 4, keywords: ["rest", "recovery", "stillness"], meaningUpright: "Rest is not retreat — it's how you rebuild your desire and clarity.", meaningReversed: "Restlessness, re-engagement, burnout.", romanticFlavor: "Take the quiet moment. Coming back to this connection refreshed will serve you both." },
  { name: "Five of Swords", arcana: "minor", suit: "swords", number: 5, keywords: ["conflict", "dishonesty", "defeat"], meaningUpright: "Not every battle is worth winning — especially when you love someone.", meaningReversed: "Moving on, releasing grudges, reconciliation.", romanticFlavor: "Choose connection over being right. The one who steps back first often wins the most." },
  { name: "Six of Swords", arcana: "minor", suit: "swords", number: 6, keywords: ["transition", "moving on", "relief"], meaningUpright: "Moving from turbulence to calmer, truer waters.", meaningReversed: "Resistance to change, unfinished business.", romanticFlavor: "Leaving something heavy behind — and finding that on the other side, there's real peace and someone real." },
  { name: "Seven of Swords", arcana: "minor", suit: "swords", number: 7, keywords: ["deception", "strategy", "hidden truths"], meaningUpright: "Not everything has been said yet — secrets still shape the dynamic.", meaningReversed: "Coming clean, exposure, conscience.", romanticFlavor: "Someone is holding back the whole truth. Honest vulnerability will unlock more than any strategy." },
  { name: "Eight of Swords", arcana: "minor", suit: "swords", number: 8, keywords: ["restriction", "trapped", "self-limitation"], meaningUpright: "The cage you're in is largely of your own making — you can step out.", meaningReversed: "Escape, clarity, releasing fear.", romanticFlavor: "Your own fear is the only thing keeping you from this. The person you want is waiting." },
  { name: "Nine of Swords", arcana: "minor", suit: "swords", number: 9, keywords: ["anxiety", "nightmares", "worry"], meaningUpright: "The thoughts at 3am are louder than reality. This isn't as dire as it feels.", meaningReversed: "Hope returning, reaching out, relief.", romanticFlavor: "The anxiety is in your head. The connection is real. Reach out — don't spiral alone." },
  { name: "Ten of Swords", arcana: "minor", suit: "swords", number: 10, keywords: ["endings", "betrayal", "rock bottom"], meaningUpright: "A painful ending — but endings always make space for something luminous.", meaningReversed: "Recovery, rising again, survival.", romanticFlavor: "This hurt. But you're rising from it with clarity and a hunger for something genuinely good." },

  // ── PENTACLES ──
  { name: "Ace of Pentacles", arcana: "minor", suit: "pentacles", number: 1, keywords: ["opportunity", "abundance", "manifestation"], meaningUpright: "A real, grounded opportunity is forming — in love and in life.", meaningReversed: "Lost chance, greed, instability.", romanticFlavor: "Something with lasting value is beginning. This connection has genuine, material substance." },
  { name: "Two of Pentacles", arcana: "minor", suit: "pentacles", number: 2, keywords: ["balance", "adaptation", "juggling"], meaningUpright: "Keeping all the plates spinning — and doing it with style.", meaningReversed: "Overwhelm, disorganized, dropping priorities.", romanticFlavor: "You're navigating multiple desires or pulls gracefully. Trust your body to know what it needs most." },
  { name: "Three of Pentacles", arcana: "minor", suit: "pentacles", number: 3, keywords: ["teamwork", "skill", "collaboration"], meaningUpright: "Two people who are genuinely good together — in ways that compound.", meaningReversed: "Lack of teamwork, ego clash, poor planning.", romanticFlavor: "What you build together is better than anything either of you could create alone." },
  { name: "Four of Pentacles", arcana: "minor", suit: "pentacles", number: 4, keywords: ["security", "control", "conservation"], meaningUpright: "Holding on tight — but consider what you might gain by opening your hands.", meaningReversed: "Release, generosity, letting go.", romanticFlavor: "Emotional security matters — but don't clutch so hard that you squeeze the life out of what's growing." },
  { name: "Five of Pentacles", arcana: "minor", suit: "pentacles", number: 5, keywords: ["hardship", "worry", "isolation"], meaningUpright: "Struggling, but not alone — look for the warmth that's already around you.", meaningReversed: "Recovery, accepting help, renewed faith.", romanticFlavor: "In moments of vulnerability, reaching for someone real transforms struggle into intimacy." },
  { name: "Six of Pentacles", arcana: "minor", suit: "pentacles", number: 6, keywords: ["generosity", "giving", "balance"], meaningUpright: "Generosity in love — and receiving it with grace.", meaningReversed: "Strings attached, debt, inequality.", romanticFlavor: "Giving your full attention, fully receiving theirs — this reciprocity is what creates real heat." },
  { name: "Seven of Pentacles", arcana: "minor", suit: "pentacles", number: 7, keywords: ["patience", "investment", "harvest"], meaningUpright: "What you've been tending is about to show real results.", meaningReversed: "Impatience, lack of reward, poor investment.", romanticFlavor: "You've been slow, intentional, and real. This connection is about to bloom into something tangible." },
  { name: "Eight of Pentacles", arcana: "minor", suit: "pentacles", number: 8, keywords: ["mastery", "dedication", "craft"], meaningUpright: "Devoted attention — to your desires, your growth, your connections.", meaningReversed: "Mediocrity, lack of focus, perfectionism.", romanticFlavor: "The one who truly listens, who is genuinely dedicated to understanding you — that's who this card speaks to." },
  { name: "Nine of Pentacles", arcana: "minor", suit: "pentacles", number: 9, keywords: ["luxury", "independence", "self-sufficiency"], meaningUpright: "You are whole, desired, and entirely capable of receiving luxury.", meaningReversed: "Dependency, superficiality, loss.", romanticFlavor: "You don't need anyone — but choosing someone because you want them, from a place of fullness, is exquisite." },
  { name: "Ten of Pentacles", arcana: "minor", suit: "pentacles", number: 10, keywords: ["legacy", "abundance", "family"], meaningUpright: "The deepest form of lasting connection — something worth building for the long term.", meaningReversed: "Broken foundations, failed expectations.", romanticFlavor: "This connection has lasting-love energy. What you're building here has real, lasting weight." },
];

export const TAROT_TOPICS = [
  { id: "love_relationships", label: "Love & Relationships", emoji: "❤️", description: "The path of your heart and romantic connections" },
  { id: "sexual_future", label: "Passion & Desire", emoji: "🔥", description: "The intimate future between you and a special someone" },
  { id: "career_success", label: "Career & Success", emoji: "✨", description: "Ambition, achievement, and your professional path" },
  { id: "general_life", label: "General Life Path", emoji: "🌙", description: "The story your destiny is writing right now" },
  { id: "romantic_decision", label: "Decision in Romance", emoji: "🃏", description: "When the heart is torn between two paths" },
  { id: "self_growth", label: "Self-Growth & Confidence", emoji: "🌸", description: "Becoming the version of yourself you most desire" },
  { id: "obstacles_love", label: "Obstacles in Love", emoji: "🌊", description: "What stands between you and what you want" },
  { id: "timing_romance", label: "Timing of Romance", emoji: "⏳", description: "When will your desires finally be answered?" },
  { id: "spiritual_connection", label: "Spiritual Connection", emoji: "🔮", description: "The deeper soul-bond beneath what's visible" },
  { id: "family_future", label: "Family & Future Home", emoji: "🏡", description: "The foundation you are building for tomorrow" },
] as const;

export type TarotTopicId = typeof TAROT_TOPICS[number]["id"];

export function drawCards(count: number): Array<TarotCard & { reversed: boolean; position: string }> {
  const positions3 = ["Past", "Present", "Future"];
  const positions5 = ["Foundation", "Challenge", "Hidden Influence", "Advice", "Outcome"];

  const positions = count === 5 ? positions5 : positions3;
  const shuffled = [...TAROT_CARDS].sort(() => Math.random() - 0.5);

  return shuffled.slice(0, count).map((card, i) => ({
    ...card,
    reversed: Math.random() > 0.65,
    position: positions[i] ?? `Card ${i + 1}`,
  }));
}

export function getZodiacSign(birthDateStr: string): string {
  const d = new Date(birthDateStr);
  const month = d.getMonth() + 1;
  const day = d.getDate();

  if ((month === 3 && day >= 21) || (month === 4 && day <= 19)) return "Aries ♈";
  if ((month === 4 && day >= 20) || (month === 5 && day <= 20)) return "Taurus ♉";
  if ((month === 5 && day >= 21) || (month === 6 && day <= 20)) return "Gemini ♊";
  if ((month === 6 && day >= 21) || (month === 7 && day <= 22)) return "Cancer ♋";
  if ((month === 7 && day >= 23) || (month === 8 && day <= 22)) return "Leo ♌";
  if ((month === 8 && day >= 23) || (month === 9 && day <= 22)) return "Virgo ♍";
  if ((month === 9 && day >= 23) || (month === 10 && day <= 22)) return "Libra ♎";
  if ((month === 10 && day >= 23) || (month === 11 && day <= 21)) return "Scorpio ♏";
  if ((month === 11 && day >= 22) || (month === 12 && day <= 21)) return "Sagittarius ♐";
  if ((month === 12 && day >= 22) || (month === 1 && day <= 19)) return "Capricorn ♑";
  if ((month === 1 && day >= 20) || (month === 2 && day <= 18)) return "Aquarius ♒";
  return "Pisces ♓";
}
